import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const mono = Inter({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zunx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${mono.variable}`}>
        <AntdRegistry>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
